# This is a basic workflow to help you get started with Actions

name: Pin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependencies && build your project
        run: npm install && npm run build
        shell: bash

      - name: pin4everland
        id: pin4everland
        uses: 4everland/pin-action@main
        with:
          EVER_TOKEN: ${{secrets.EVER_TOKEN}}
          # EVER_PROJECT_ID: ${{secrets.EVER_PROJECT_ID}}
          EVER_PROJECT_NAME: "vue-test-ar"
          EVER_PROJECT_PLAT: "AR"
          BUILD_LOCATION: "./dist"
      - name: echo ipfs
        run: echo ${{ steps.pin4everland.outputs.uri }}
